import { StyleSheet } from "react-native";
import { color } from "../../constants/Constants";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: "column",
      marginHorizontal: 20,
      alignItems: "center",
      justifyContent: "space-evenly",
    },
    profile: {
      alignItems: "center",
      justifyContent: "center",
    },
    profileText: {
      fontFamily: "Petrona-Regular",
      fontSize: 16,
      color: "#000000",
    },
    contact: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
    },
    contactText: {
      fontFamily: "Petrona-Regular",
      fontSize: 10,
      color: "rgba(0, 0, 0, 0.56)",
      marginHorizontal: 4,
    },
    profileDetailes: {
      alignItems: "center",
      justifyContent: "space-around",
      display: "flex",
      flexDirection: "column",
    },
    language: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      marginVertical: 10,
      width: 315,
      height: 50,
      borderRadius: 11,
      borderColor:color.secondary,
      borderWidth: 2,
      textAlign: "center",
    },
    mainText: {
      fontFamily: "Petrona-Regular",
      fontSize: 14,
      color: "#000000",
    },
    secondText: {
      fontFamily: "Petrona-Regular",
      fontSize: 14,
      color: "rgba(0, 0, 0, 0.56)",
    },
    textIcon: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    icon: {
      backgroundColor: color.secondary,
      width: 30,
      height: 25.862,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 15,
      textAlign: "center",
    },
    rateShare: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
      marginVertical: 10,
    },
    share: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
      marginHorizontal: 15,
      width: 143,
      height: 50,
      borderRadius: 11,
      borderColor: color.secondary,
      borderWidth: 2,
      textAlign: "center",
    },
    logout: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      marginVertical: 10,
      width: 315,
      height: 50,
      borderRadius: 11,
      backgroundColor: color.primary,
      textAlign: "center",
    },
    logoutText: {
      fontFamily: "Petrona-Medium",
      fontSize: 14,
      color: "#ffffff",
    },
  });